model:
  base_model: "naver-clova-ix/donut-base-finetuned-cord-v2"

dataset:
  local_path: "./dataset/donut_dataset.jsonl"
  input_col: "image_path"
  output_col: "output"

training:
  micro_batch_size: 1
  learning_rate: 5e-5
  num_epochs: 3
  gradient_checkpointing: true

output_dir: "outputs/donut-finetuned"
