name: Build and Push Docker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pobranie repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Logowanie do GHCR (Twoje konto)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3️⃣ Budowa i wypchnięcie obrazu
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/wshoq/donut-train:latest
